FROM vvakame/review:3.2
RUN npm install -g \
    textlint@11.3.1 \
    power-assert \
    textlint-rule-max-ten \
    textlint-rule-spellcheck-tech-word \
    textlint-rule-no-mix-dearu-desumasu \
    textlint-rule-prh \
    textlint-filter-rule-comments
RUN npm install -g \
    git://github.com/matsubara0507/textlint-plugin-review.git#50f4da0
